import React, { ReactNode } from 'react';
import './globals.scss';

export const metadata = {
  title: 'My Next.js App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
